{application,skirmish_srv,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{skirmish_srv_app,[]}},
              {env,[]},
              {modules,[skirmish_battle,skirmish_battle_sup,skirmish_srv,
                        skirmish_srv_app,skirmish_sup]}]}.
