{application,sws_srv,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{sws_srv_app,[]}},
              {env,[]},
              {modules,[galaxy_helper,simulation_callback,sws_srv,sws_srv_app,
                        sws_srv_sup,rest_callback]}]}.
