{application,force_srv,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{force_srv_app,[]}},
              {env,[]},
              {modules,[force_sim,force_sim_sup,force_srv,force_srv_app,
                        force_srv_sup]}]}.
