{application,faction_srv,
             [{description,"Faction and strategy simulation server"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{faction_srv_app,[]}},
              {env,[]},
              {modules,[empire_strategy,faction_srv,faction_srv_app,
                        faction_srv_sup,faction_strategy_sim,
                        faction_strategy_sup,mnesia_faction]}]}.
